"""Turns a saved case back into reference findings. No Qt here.

A case stores only what the student entered (symptom ids and parameters,
vitals, medicine and condition ids). Every time it is opened, the findings
are worked out again from today's reference data:

    symptom case       the correlation engine, shown as counts (its symptoms,
                       explains yours), not a percentage
    interaction case   the drug-safety engine, with the same verdicts

So a case never shows a result the database no longer supports.

Also here: de-identified age ranges and the "Start a vignette for me"
template. The template is fixed text built from the inputs, not AI.
"""

import html
from dataclasses import asdict
from datetime import datetime
from typing import Optional

from app.models.checker import (
    COMORBIDITIES,
    DURATIONS,
    EXPOSURES,
    FAMILY_RISKS,
    ONSETS,
    PATTERNS,
    TRENDS,
    CheckerInput,
    CheckerResult,
    SelectedSymptom,
    Vitals,
)

# (label, lowest age, highest age)
AGE_RANGES = (
    ("0–4", 0, 4), ("5–12", 5, 12), ("13–17", 13, 17), ("18–24", 18, 24),
    ("25–34", 25, 34), ("35–44", 35, 44), ("45–54", 45, 54), ("55–64", 55, 64),
    ("65–74", 65, 74), ("75–84", 75, 84), ("85+", 85, 110),
)
SETTINGS = ("Outpatient clinic", "Emergency department", "Inpatient ward", "Community")
DIFFICULTIES = ("Beginner", "Intermediate", "Advanced")
SEXES = (("female", "Female"), ("male", "Male"))

# Same wording as the Drug Interaction Checker's badges.
VERDICT_TEXT = {
    "compatible": ("NO INTERACTIONS ON RECORD", "success"),
    "no_flags": ("NO FLAGS, GAPS IN DATA", "primary"),
    "caution": ("PRECAUTIONS ON RECORD", "amber"),
    "avoid": ("SIGNIFICANT INTERACTION ON RECORD", "danger"),
}
SEVERITY_TEXT = {"safe": "Compatible", "caution": "Precaution", "avoid": "Avoid",
                 "unknown": "Not on record"}


def age_range(age: int) -> str:
    return next((label for label, low, high in AGE_RANGES if low <= age <= high), "85+")


def range_midpoint(label: str) -> int:
    """The engine needs a number; a range's middle is close enough and keeps
    the saved case de-identified."""
    for name, low, high in AGE_RANGES:
        if name == label:
            return (low + min(high, 90)) // 2
    return 30


def vitals_flags(v: Vitals) -> dict[str, bool]:
    """Which vitals sit outside typical adult resting ranges. Descriptive
    only: the case column shows "outside typical range", never advice."""
    return {
        "temperature": v.temperature >= 38.0 or v.temperature < 36.0,
        "heart_rate": v.heart_rate > 100 or v.heart_rate < 60,
        "blood_pressure": v.bp_systolic >= 140 or v.bp_systolic < 90 or v.bp_diastolic >= 90,
        "spo2": v.spo2 < 95,
        "resp_rate": v.resp_rate > 20 or v.resp_rate < 12,
    }


def checker_input_to_case(data: CheckerInput) -> dict:
    """What a symptom case stores from the checker. The exact age is
    replaced by a range."""
    return {
        "symptoms": [asdict(s) for s in data.symptoms],
        "vitals": asdict(data.vitals),
        "age_range": age_range(data.age),
        "sex": data.sex,
        "exposures": sorted(data.exposures),
        "comorbidities": sorted(data.comorbidities),
        "family_history": sorted(data.family_history),
    }


def case_to_checker_input(case: dict) -> CheckerInput:
    known = set(SelectedSymptom.__dataclass_fields__)
    symptoms = [SelectedSymptom(**{k: v for k, v in s.items() if k in known})
                for s in case.get("symptoms", [])]
    vitals_known = set(Vitals.__dataclass_fields__)
    vitals = Vitals(**{k: v for k, v in case.get("vitals", {}).items() if k in vitals_known})
    return CheckerInput(symptoms=symptoms, vitals=vitals,
                        age=range_midpoint(case.get("age_range", "")),
                        sex=case.get("sex", "female"),
                        exposures=set(case.get("exposures", [])),
                        comorbidities=set(case.get("comorbidities", [])),
                        family_history=set(case.get("family_history", [])))


def label_lists(case: dict) -> dict[str, list[str]]:
    """Readable names for the exposure / comorbidity / family-history ids."""
    exposures = {k: label for k, label, _kw in EXPOSURES}
    comorbid = {k: label for k, label, _kw in COMORBIDITIES}
    family = {k: label for k, label, *_rest in FAMILY_RISKS}
    return {
        "exposures": [exposures.get(k, k) for k in case.get("exposures", [])],
        "comorbidities": [comorbid.get(k, k) for k in case.get("comorbidities", [])],
        "family_history": [family.get(k, k) for k in case.get("family_history", [])],
    }


def vignette_template(case: dict, setting: str) -> str:
    """ "Start a vignette for me": a fixed sentence built from the inputs,
    for the student to rewrite. Not generated by AI."""
    durations = dict(DURATIONS)
    sex = dict(SEXES).get(case.get("sex", ""), "patient").lower()
    parts = []
    for s in case.get("symptoms", []):
        detail = [f"{s.get('intensity', 0)}/10", s.get("onset", "")]
        duration = durations.get(s.get("duration", ""), "")
        if duration:
            detail.append(duration.lower())
        parts.append(f"{s.get('name', '').lower()} ({', '.join(d for d in detail if d)})")
    complaint = ", ".join(parts[:-1]) + (f" and {parts[-1]}" if len(parts) > 1 else
                                          (parts[0] if parts else "no reported symptoms"))
    where = setting.lower() if setting else "clinic"
    text = f"A {case.get('age_range', '')} y/o {sex} presents to the {where} with {complaint}."
    v = case.get("vitals", {})
    if v:
        text += (f" Recorded vitals: T {v.get('temperature', 0):.1f} °C, HR {v.get('heart_rate')}, "
                 f"BP {v.get('bp_systolic')}/{v.get('bp_diastolic')}, RR {v.get('resp_rate')}, "
                 f"SpO₂ {v.get('spo2')}%.")
    labels = label_lists(case)
    if labels["comorbidities"]:
        text += " History of " + ", ".join(x.lower() for x in labels["comorbidities"]) + "."
    if labels["exposures"]:
        text += " Reports " + ", ".join(x.lower() for x in labels["exposures"]) + "."
    return text


# ----------------------------------------------------------------------
#   "Add case summary to my notes"
# ----------------------------------------------------------------------

_TABLE = ('<table border="1" cellspacing="0" cellpadding="6" width="100%" '
          'style="border-collapse: collapse; border-color: #6B7280;">')


def _e(text) -> str:
    return html.escape(str(text))


def _table(headers: list[str], rows: list[list[str]]) -> str:
    head = "".join(f"<th>{_e(h)}</th>" for h in headers)
    body = "".join("<tr>" + "".join(f"<td>{_e(c)}</td>" for c in row) + "</tr>"
                   for row in rows)
    return f"{_TABLE}<tr>{head}</tr>{body}</table>"


URGENCY_TEXT = {"EMERGENCY": "Emergency", "SEEK_URGENT_CARE": "Urgent",
                "SEE_DOCTOR_SOON": "See doctor soon", "SELF_CARE": "Self-care"}


def correlation_table(case: dict, result: Optional[CheckerResult],
                      limit: int = 8) -> tuple[list[str], list[list[str]]]:
    """Hallmark correlation as table rows: counts, not a probability.
    "Its symptoms" = reported / listed for the condition; "Explains" =
    reported symptoms the condition lists / all reported symptoms."""
    names = [s.get("name", "") for s in case.get("symptoms", [])]
    headers = ["Condition", *names, "Reference urgency", "Its symptoms", "Explains yours"]
    rows = []
    for match in (result.matches[:limit] if result else []):
        matched = {m.name: m for m in match.matched}
        cells = []
        for name in names:
            entry = matched.get(name)
            if entry is not None:
                cells.append("● Hallmark" if entry.is_primary else "● Present")
            elif name in match.inconsistent:
                cells.append("— Not linked")
            else:
                cells.append("—")
        rows.append([match.name, *cells, URGENCY_TEXT.get(match.urgency, "Not specified"),
                     f"{match.matched_count}/{match.total_hallmarks}",
                     f"{match.explained_count}/{match.reported_count}"])
    return headers, rows


def symptom_summary_html(title: str, case: dict, result: Optional[CheckerResult],
                         closing: bool = True) -> str:
    """The case written out as notes the student can annotate. The answer
    key is left out on purpose, so the summary never gives it away."""
    sexes = dict(SEXES)
    parts = [f"<h2>Case summary: {_e(title)}</h2>",
             "<p><i>Hypothetical study case. Findings recomputed from the reference data on "
             f"{datetime.now():%b %d, %Y}.</i></p>"]
    facts = [f"{case.get('age_range', '?')} y/o", sexes.get(case.get("sex", ""), ""),
             case.get("setting", ""), case.get("difficulty", "")]
    parts.append("<p><b>" + _e(" · ".join(f for f in facts if f)) + "</b></p>")
    if case.get("chief_complaint"):
        parts.append(f"<p><i>“{_e(case['chief_complaint'])}”</i></p>")
    if case.get("vignette"):
        parts.append(f"<p>{_e(case['vignette'])}</p>")

    names = {"onset": dict(ONSETS), "pattern": dict(PATTERNS), "trend": dict(TRENDS),
             "duration": dict(DURATIONS)}
    symptoms = case.get("symptoms", [])
    if symptoms:
        parts.append("<h3>Reported symptoms</h3>")
        parts.append(_table(
            ["Symptom", "Intensity", "Onset", "Pattern", "Trend", "Duration"],
            [[s.get("name", ""), f"{s.get('intensity', 0)}/10",
              names["onset"].get(s.get("onset"), ""), names["pattern"].get(s.get("pattern"), ""),
              names["trend"].get(s.get("trend"), ""), names["duration"].get(s.get("duration"), "")]
             for s in symptoms]))

    raw = case.get("vitals")
    if raw:
        v = Vitals(**{k: val for k, val in raw.items() if k in Vitals.__dataclass_fields__})
        flags = vitals_flags(v)
        mark = lambda key, text: f"{text} *" if flags[key] else text  # noqa: E731
        parts.append("<h3>Recorded vitals</h3>")
        parts.append(_table(["Temp", "HR", "BP", "RR", "SpO₂"], [[
            mark("temperature", f"{v.temperature:.1f} °C"), mark("heart_rate", f"{v.heart_rate}"),
            mark("blood_pressure", f"{v.bp_systolic}/{v.bp_diastolic}"),
            mark("resp_rate", f"{v.resp_rate}"), mark("spo2", f"{v.spo2}%")]]))
        if any(flags.values()):
            parts.append("<p><small>* outside typical adult resting range</small></p>")

    labels = label_lists(case)
    for caption, key in (("Comorbidities", "comorbidities"), ("Exposures", "exposures"),
                         ("Family history", "family_history")):
        if labels[key]:
            parts.append(f"<p><b>{caption}:</b> {_e(', '.join(labels[key]))}</p>")

    headers, rows = correlation_table(case, result)
    if rows:
        parts.append("<h3>Hallmark correlation (reference)</h3>")
        parts.append(_table(headers, rows))

    objectives = [o for o in case.get("objectives", []) if o.strip()]
    if objectives:
        parts.append("<h3>Learning objectives</h3><ul>"
                     + "".join(f"<li>{_e(o)}</li>" for o in objectives) + "</ul>")
    if closing:
        parts.append("<h3>My notes</h3><p></p>")
    return "".join(parts)


def interaction_summary_html(title: str, case: dict, data: Optional[dict],
                             heading: str = "Case summary") -> str:
    parts = [f"<h2>{_e(heading)}: {_e(title)}</h2>",
             "<p><i>Hypothetical study case. Findings recomputed from the reference data on "
             f"{datetime.now():%b %d, %Y}.</i></p>"]
    if data:
        parts.append(f"<p><b>{_e(data['verdict'][0])}</b></p>")
        parts.append(f"<p><b>Candidate drug:</b> {_e(data.get('candidate') or 'Not in reference data')}</p>")
        parts.append(f"<p><b>Case regimen:</b> {_e(', '.join(data.get('regimen', [])) or 'none')}</p>")
        parts.append("<p><b>Case comorbidities:</b> "
                     f"{_e(', '.join(data.get('conditions', [])) or 'none')}</p>")
        if data.get("rows"):
            parts.append("<h3>Findings on record</h3>")
            parts.append(_table(data["headers"], data["rows"]))
    if case.get("notes"):
        parts.append(f"<p>{_e(case['notes'])}</p>")
    parts.append("<h3>My notes</h3><p></p>")
    return "".join(parts)


class CaseReference:
    """Works cases out again from the reference data."""

    def __init__(self, engine=None, safety=None, medicines=None) -> None:
        self._engine = engine          # MatchingService
        self._safety = safety          # DrugSafetyService
        self._medicines = medicines    # MedicineService

    # ------------------------------------------------------ symptom cases

    def symptom_result(self, case: dict) -> Optional[CheckerResult]:
        if self._engine is None or not case.get("symptoms"):
            return None
        try:
            return self._engine.evaluate(case_to_checker_input(case))
        except Exception:
            return None

    # -------------------------------------------------- interaction cases

    def interaction(self, case: dict) -> Optional[dict]:
        """Names, today's verdict and every finding as table rows."""
        if self._safety is None:
            return None
        names = {m.id: m.name for m in self._medicines.all_medicines()} \
            if self._medicines else {}
        labels = {c.id: c.label for c in self._safety.conditions()}
        candidate_id = case.get("candidate_id", "")
        regimen = list(case.get("regimen_ids", []))
        conditions = set(case.get("condition_ids", []))
        candidate = self._safety.drug_for("", candidate_id, is_candidate=True)
        drugs = [self._safety.drug_for("", m) for m in regimen]
        report = self._safety.evaluate(candidate, drugs, conditions)

        rows = []
        for rule in report.rules:
            rows.append(["Combination rule", " + ".join(d.name for d in rule.drugs),
                         SEVERITY_TEXT.get(rule.rule.severity, rule.rule.severity),
                         rule.rule.description])
        for f in report.conditions:
            rows.append(["Drug × condition", f"{f.drug.name} × {f.condition.label}",
                         SEVERITY_TEXT.get(f.severity, f.severity), f.summary])
        for p in report.pairs:
            rows.append(["Drug × drug", f"{p.first.name} + {p.second.name}",
                         SEVERITY_TEXT.get(p.severity, p.severity), p.description])
        text, tone = VERDICT_TEXT.get(report.verdict, ("", "muted"))
        return {"candidate": names.get(candidate_id, ""),
                "regimen": [names.get(m, "Not in reference data") for m in regimen],
                "conditions": [labels.get(c, c) for c in case.get("condition_ids", [])],
                "verdict": (text, tone),
                "headers": ["Layer", "Combination", "On record", "Reference note"],
                "rows": rows}

    # ------------------------------------------------------------ summary

    def summary_html(self, item) -> str:
        """Everything attached to a note or case, written out for the notes.
        The answer key is never included."""
        symptom, interaction = item.symptom_data, item.interaction_data
        parts = []
        if symptom.get("symptoms"):
            parts.append(symptom_summary_html(item.title, symptom, self.symptom_result(symptom),
                                              closing=not interaction.get("candidate_id")))
        if interaction.get("candidate_id"):
            try:
                data = self.interaction(interaction)
            except Exception:
                data = None
            heading = "Drug interaction check" if parts else "Case summary"
            parts.append(interaction_summary_html(item.title, interaction, data, heading))
        return "".join(parts)

    def symptom_overview(self, symptom: dict) -> Optional[dict]:
        """A one-glance line for the quick view."""
        if not symptom.get("symptoms"):
            return None
        result = self.symptom_result(symptom)
        top = result.matches[0] if result and result.matches else None
        return {"symptoms": [s.get("name", "") for s in symptom.get("symptoms", [])],
                "facts": " · ".join(x for x in (
                    f"{symptom.get('age_range', '?')} y/o",
                    dict(SEXES).get(symptom.get("sex", ""), ""),
                    symptom.get("setting", "")) if x),
                "top": f"{top.name} · {top.matched_count}/{top.total_hallmarks} of its symptoms, "
                       f"explains {top.explained_count}/{top.reported_count} of the reported"
                       if top else "No condition matches on record"}
