"""Daily health tips for the dashboard, read from data/health_tips.json.

The tips are content, so they are written by the project team (not
generated by the app) and each one names its source, the same rule as the
encyclopedia's references. One tip is shown per day, the same tip all day,
A random tip is picked each time the dashboard is shown (never the same one
twice in a row). If the file is missing or empty, the built-in tips below
are used, so the card never goes blank.

File format:

    {
      "tips": [
        {"text": "One or two plain-language sentences.",
         "source": "Department of Health (DOH), Philippines",
         "url": "https://..."}
      ]
    }
"""

import json
import random
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Optional

from app.core.paths import resource

DEFAULT_TIPS_PATH = resource("data", "health_tips.json")


@dataclass
class HealthTip:
    text: str
    source: str = ""
    url: str = ""



# Same as data/health_tips.json at the time of writing (WHO fact sheets).
BUILT_IN_TIPS = [
    HealthTip('Aim for at least 400 grams of fruits and vegetables a day, about five portions, to lower your risk of diet-related diseases.',
              'World Health Organization: Healthy diet',
              'https://www.who.int/news-room/fact-sheets/detail/healthy-diet'),
    HealthTip('Keep salt below 5 grams a day, about one level teaspoon, counting the salt already in sauces, instant noodles and processed food.',
              'World Health Organization: Healthy diet',
              'https://www.who.int/news-room/fact-sheets/detail/healthy-diet'),
    HealthTip('Limit free sugars (added sugar, syrups, sweetened drinks and juices) to less than 10% of your daily energy intake.',
              'World Health Organization: Healthy diet',
              'https://www.who.int/news-room/fact-sheets/detail/healthy-diet'),
    HealthTip('Adults should get at least 150 minutes of moderate-intensity physical activity a week, and cut down on time spent sitting.',
              'World Health Organization: Physical activity',
              'https://www.who.int/news-room/fact-sheets/detail/physical-activity'),
    HealthTip('Cover, empty and clean water containers around your home every week, so dengue mosquitoes have nowhere to breed.',
              'World Health Organization: Dengue and severe dengue',
              'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue'),
    HealthTip('Dengue mosquitoes bite during the day: wear clothes that cover your arms and legs and use a repellent with DEET, picaridin or IR3535.',
              'World Health Organization: Dengue and severe dengue',
              'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue'),
]


class HealthTipRepository:
    def __init__(self, path: Optional[Path] = None) -> None:
        self._path = path or DEFAULT_TIPS_PATH
        self._cache: Optional[list[HealthTip]] = None
        self._mtime = 0.0

    def all(self) -> list[HealthTip]:
        """Re-read only when the file changed, so editing it shows on the next visit."""
        try:
            mtime = self._path.stat().st_mtime
        except OSError:
            return []
        if self._cache is None or mtime != self._mtime:
            self._mtime = mtime
            try:
                raw = json.loads(self._path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                raw = {}
            tips = raw.get("tips") if isinstance(raw, dict) else None
            self._cache = [
                HealthTip(str(t.get("text", "")).strip(), str(t.get("source", "")).strip(),
                          str(t.get("url", "")).strip())
                for t in (tips or []) if isinstance(t, dict) and str(t.get("text", "")).strip()
            ]
        return self._cache

    def tips(self) -> list[HealthTip]:
        """The file's tips, or the built-in ones when the file has none."""
        return self.all() or BUILT_IN_TIPS

    def tip_for_today(self, today: Optional[date] = None) -> Optional[HealthTip]:
        tips = self.tips()
        return tips[(today or date.today()).toordinal() % len(tips)] if tips else None

    def random_tip(self, previous: Optional[HealthTip] = None) -> Optional[HealthTip]:
        """Any tip but the one shown last time."""
        tips = self.tips()
        if not tips:
            return None
        choices = [t for t in tips if previous is None or t.text != previous.text] or tips
        return random.choice(choices)
